platform :ios, '11.2'
use_frameworks!

target 'Dashi' do
  pod 'Alamofire', '~> 4.5'
  pod 'PromiseKit/Alamofire', '~> 4.0'
  pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '2.x'
  pod 'SwiftyJSON'
  pod 'Arcane'
end
